# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'GeoPix' do

source 'https://github.com/CocoaPods/Specs.git'

pod 'IMFFacebookAuthentication'
pod 'IMFPush'
pod 'IMFData'
pod 'IMFURLProtocol'
pod 'IMFCore'

end

target 'GeoPixTests' do

end

